apiVersion: operations.operator.io/v1alpha1
kind: Project
metadata:
  labels:
    app.kubernetes.io/name: project
    app.kubernetes.io/instance: project-sample
    app.kubernetes.io/part-of: project-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: project-operator
  name: project-sample
spec:
  members:
    - clarke.armstrong
    - bray.ferguson
    - hansen.rivera
  environments:
    - name: dev
      resources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 1
          memory: 1Gi
    - name: test
      resources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 1
          memory: 1Gi
    - name: prod
      resources:
        requests:
          cpu: 2
          memory: 4Gi
        limits:
          cpu: 2
          memory: 4Gi
